// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "algopt/rebalancer/solver/moves/MoveType.h"

namespace facebook::rebalancer {

class Problem;

// These move types are used specifically by RAS stackable solve, where "server
// parts" are objects, "reservations" are containers and "servers" are
// groups. Equivalent sets are group of servers (and by extension their parts)
// that are identical from local search's perspective. We require that all parts
// of a server must belong to the same equivalent set.
// an object bundle is collection of server parts that belong to the same server
// and will ve moved togather
using ObjectBundle = std::vector<entities::ObjectId>;

enum class EquivalenceSetType {
  // Computed using search space partition
  SEARCH_SPACE_PARTITION = 0,
  // Computed by Rebalancer using all goals and constraints
  ALL_GOALS_AND_CONSTRAINTS = 1,
  // Computed on demand using the search space + select goals and constraints
  SELECT_GOALS_AND_CONSTRAINTS = 2,
};

constexpr folly::StringPiece kAllowedScopeItemsPerGroupAttrName =
    "allowedScopeItemsPerGroupAttr";

constexpr folly::StringPiece kGpuTopologyOverlapTrackerAttrName =
    "GpuTopologyOverlapTracker";

// in some cases, such as 1:k SWAP move types, we may still want to select
// multiple objects even in the adaptive allotment universe. This config setting
// will store the necessary parameters
struct MultiObjectSelectionConfig {
  std::function<int(entities::GroupId)> getBundleSizeForGroup;
};

// These move types are used with a hot container and a special container
// For fixed source move types: unassigned (special) --> hot container
// For fixed destination move types: hot container --> unassigned (special)
template <typename MoveTypeSpecT>
class FixedSrcDstMoveCandidateGenerator {
 public:
  explicit FixedSrcDstMoveCandidateGenerator(const MoveTypeSpecT& spec)
      : spec_(spec) {}

  // For stackable move types, we need to move bundles of objects (server parts)
  // together from the source container. In order to perform moves, we would
  // need enough server parts > bundle-size in the source container.
  // This function does two things:
  // - First, it filters out all the objects that do not have enough such
  //  server parts.
  // - Second, it uses the searchSpacePartition to further restrict the search
  //  space by filtering out redundant sever-part groups
  //
  // This function also lazily updates the curentSourceObjects_ index by
  // removing all the objects that are no longer in the source container.
  //
  // Returns:  a list of objectBundles which are essentially the move candidates
  // generated by this generator
  std::vector<ObjectBundle>
  filterSourceObjectsByBundleSizeAndSearchSpacePartition(
      const MovesEvaluator& evaluator,
      entities::ContainerId srcContainer,
      entities::ContainerId dstContainer,
      std::optional<MultiObjectSelectionConfig> multiObjSelectionConfig =
          std::nullopt);

 private:
  int getMultiMoveBundleSize(
      entities::ContainerId srcContainer,
      entities::ContainerId dstContainer,
      const entities::Universe& universe);

  // Helper function to print useful debug information about move candidates
  static std::string getDebugInfo(
      entities::ContainerId srcContainer,
      entities::ContainerId dstContainer,
      const std::vector<ObjectBundle>& moveCandidates,
      const entities::Universe& universe);

  MoveTypeSpecT spec_;
};

// This move types attempts to move MULTIPLE objects from a pre-specified
// "special container" (fixed source) to the hot container  or vice versa
// such that the objective is improved
// This is an abstract class and FixedSource and FixedDest versions will
// inherit from it
template <typename MoveTypeSpecT>
class FixedSrcDstMultiMoveType : public MoveType {
 public:
  explicit FixedSrcDstMultiMoveType(
      const interface::LocalSearchSolverSpec& solverConfigs,
      const MoveTypeSpecT& spec)
      : MoveType(solverConfigs), moveCandidateGenerator_(spec), spec_(spec) {}

 protected:
  MoveResult findBestMoveHelper(
      const MovesEvaluator& evaluator,
      entities::ContainerId srcContainer,
      entities::ContainerId dstContainer,
      MoveStatsAggregator& stats,
      const SearchHints& hints,
      double timeLimit);

  FixedSrcDstMoveCandidateGenerator<MoveTypeSpecT> moveCandidateGenerator_;
  MoveTypeSpecT spec_;
};
} // namespace facebook::rebalancer
