// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "algopt/rebalancer/solver/moves/AsyncSingleMovesMoveType.h"

namespace facebook::rebalancer {

constexpr folly::StringPiece kSingleEndChainMoveTypeName = "SINGLE_END_CHAIN";

// For each possible pair of objects {o1, o2} (where o1 is and object in the hot
// container), perform 2 moves concurrently:
// 1. Move o1 to the source of o2.
// 2. Move o2 to each possible destination.
// It can be thought of as a chain of length 2, where one object moves to a
// container, and another object from that container moves to a different one.
// The number of neighbors generated by this move type alone is, approximately:
// #containers * #objects ^ 2
class SingleEndChainMoveType : public AsyncSingleMovesMoveType {
 public:
  std::string name() const override;

  explicit SingleEndChainMoveType(
      const interface::LocalSearchSolverSpec& solverConfigs,
      const interface::SingleEndChainMoveTypeSpec& spec);
  MoveResult exploreFromAllSingleMoves(
      const MovesEvaluator& evaluator,
      entities::ContainerId hot_container,
      entities::ObjectId hotObject,
      entities::ContainerId cold_container,
      MoveStatsAggregator& stats) override;

 private:
  interface::SingleEndChainMoveTypeSpec spec_;
};
} // namespace facebook::rebalancer
