// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "algopt/rebalancer/solver/moves/AsyncSingleMovesMoveType.h"

namespace facebook::rebalancer {

constexpr folly::StringPiece kSingleChainMoveTypeName = "SINGLE_CHAIN";

// For each possible pair of objects {o1, o2} (where o2 is an object in the hot
// container), perform 2 moves concurrently:
// 1. Move o1 to the source of o2.
// 2. Move o2 to each possible destination.
// It can be thought of as a chain of length 2, where one object moves to a
// container, and another object from that container moves to a different one.
// The number of neighbors generated by this move type alone is, approximately:
// #containers * #objects ^ 2
class SingleChainMoveType : public AsyncSingleMovesMoveType {
 public:
  std::string name() const override;

  explicit SingleChainMoveType(
      const interface::LocalSearchSolverSpec& solverConfigs,
      const interface::SingleChainMoveTypeSpec& spec);

  MoveResult exploreFromAllSingleMoves(
      const MovesEvaluator& evaluator,
      entities::ContainerId hotContainer,
      entities::ObjectId hotObject,
      entities::ContainerId coldContainer,
      MoveStatsAggregator& stats) override;

  std::optional<PackerSet<entities::ContainerId>> getCustomColdContainers(
      const MovesEvaluator& evaluator,
      entities::ContainerId /*hotContainer*/) const override;

 protected:
  MoveResult exploreChainsWithHotObjectToColdContainer(
      const MovesEvaluator& evaluator,
      entities::ContainerId hotContainer,
      entities::ObjectId hotObject,
      entities::ContainerId coldContainer,
      MoveStatsAggregator& stats,
      bool greedy);

  static MoveResult exploreWithinGroupAndGetBestResult(
      const MovesEvaluator& evaluator,
      entities::ContainerId hotContainer,
      entities::ObjectId hotObject,
      entities::ContainerId coldContainer,
      entities::ContainerId otherContainer,
      const std::string& partitionName,
      MoveStatsAggregator& stats,
      bool greedy);

  static MoveResult exploreAllAndGetBestResult(
      const MovesEvaluator& evaluator,
      entities::ContainerId hotContainer,
      entities::ObjectId hotObject,
      entities::ContainerId coldContainer,
      entities::ContainerId otherContainer,
      MoveStatsAggregator& stats,
      bool greedy);

  static MoveResult generateMoveSetAndGetResult(
      const MovesEvaluator& evaluator,
      entities::ObjectId hotObject,
      entities::ContainerId hotContainer,
      entities::ContainerId coldContainer,
      entities::ObjectId otherObject,
      entities::ContainerId otherContainer,
      MoveStatsAggregator& stats);

 protected:
  virtual std::optional<std::string>
  getPartitionNameToExploreChainsWithinObjectGroup() const {
    return partitionNameToExploreChainsWithinObjectGroup_;
  }
  virtual std::optional<std::string> getSpecialColdContainer() const {
    return specialColdContainer_;
  }

 private:
  std::optional<std::string> partitionNameToExploreChainsWithinObjectGroup_ =
      std::nullopt;
  std::optional<std::string> specialColdContainer_ = std::nullopt;
};
} // namespace facebook::rebalancer
